name: Docker Image SUITE_SUITE_SERVICE CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: production application file setting
        run: |
          mkdir -p ./src/main/resources
          touch ./src/main/resources/application.yml

      - name: production test application file setting
        run: |
          mkdir -p ./src/test/resources
          touch ./src/test/resources/application.yml
          echo ${{TEST_APPLICATION_YML}} | base64 --decode >> ./src/test/resources/application.yml

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Init with Gradle
        uses: gradle/gradle-build-action@v2
      - run: gradle init

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test
        
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.1.1
          arguments: build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 ## 자신의 리전

      - name: Check if image with tag exists
        id: check-image
        run: |
          if aws ecr describe-images --repository-name suite-ecr --image-ids imageTag=suite-suite-service-latest; then
            echo "Image with tag $IMAGE_TAG exists in repository $REPOSITORY"
            echo "::set-output name=image_exists::true"
          else
            echo "Image with tag $IMAGE_TAG does not exist in repository $REPOSITORY"
            echo "::set-output name=image_exists::false"
          fi

      - name: Delete existing image with the same tag
        if: steps.check-image.outputs.image_exists == 'true'
        run: |
          aws ecr batch-delete-image --repository suite-ecr --image-ids imageTag=suite-suite-service-latest
      

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1



      - name: Build & Push to ECR
        run: |
          docker build -t suite-ecr:suite-suite-service-latest .
          docker tag suite-ecr:suite-suite-service-latest ${{ secrets.AWS_ACCOUNT_NUM }}.dkr.ecr.ap-northeast-2.amazonaws.com/suite-ecr:suite-suite-service-latest
          docker push ${{ secrets.AWS_ACCOUNT_NUM }}.dkr.ecr.ap-northeast-2.amazonaws.com/suite-ecr:suite-suite-service-latest
